[username]
style_user = "green bold"
style_root = "red bold"
format = "[╭─╴](blue bold)[$user]($style)"
show_always = true

[hostname]
ssh_only = false
format = '[@](bold blue)[$hostname](bold yellow) '

[directory]
style = "bold italic cyan"
truncation_length = 0
truncate_to_repo = true
truncation_symbol = "repo: "

[character]
success_symbol = "[╰─╴\\$](bold blue)"
error_symbol = "[╰─╴\\$](bold blue)"
