[character]
success_symbol = "[\\$](bold green)"
error_symbol = "[\\$](bold red)"

[cmd_duration]
min_time = 10_000   # 10 seconds
format = "took [$duration]($style) "
show_milliseconds = true

[directory]
style = "bold italic cyan"
truncation_length = 0
truncate_to_repo = true
truncation_symbol = "repo: "

[username]
style_user = "bold green"
style_root = "bold red"
show_always = true
format = "[$user]($style)"

[hostname]
ssh_only = false
style = "bold yellow"
format = "[@](bold bright black)[$hostname]($style) "
disabled = false
