# [line_break]
# disabled = true

palette = "carbonfox"

[palettes.carbonfox]
red = "#ee5396"
green = "#25be6a"
purple = "#be95ff"
yellow = "#08bdba"
os_bg = "#7b7c7e"
os_fg = "#0c0c0c"
dir_bg = "#25be6a"
dir_fg = "#161616"
git_bg = "#08bdba"
git_fg = "#252525"
lang_bg = "#78a9ff"
lang_fg = "#353535"

[character]
success_symbol = "[➜](bold blue)"
error_symbol = "[➜](bold red)"

[cmd_duration]
min_time = 1 
format = "took [$duration]($style) "
show_milliseconds = true

[directory]
style = "bold italic cyan"
format = "[$path]($style) "
truncation_length = 0
truncate_to_repo = true
truncation_symbol = "repo: "

[username]
style_user = "bold green"
style_root = "bold red"
show_always = true
format = "[$user]($style)"

[hostname]
ssh_only = false
style = "bold yellow"
format = "[@](bold bright black)[$hostname]($style) "
disabled = false
