add_newline = false

palette = "carbonfox"

[palettes.carbonfox]
red = "#ee5396"
green = "#25be6a"
purple = "#be95ff"
yellow = "#08bdba"
os_bg = "#7b7c7e"
os_fg = "#0c0c0c"
dir_bg = "#25be6a"
dir_fg = "#161616"
git_bg = "#08bdba"
git_fg = "#252525"
lang_bg = "#78a9ff"
lang_fg = "#353535"

format = """
$username\
$hostname\
$directory\
$git_branch\
$git_state\
$git_status\
$cmd_duration\
$line_break\
$python\
$character"""

[directory]
style = "italic bold cyan"
read_only = " ro"

[character]
success_symbol = "[❯](purple)"
error_symbol = "[❯](red)"
vimcmd_symbol = "[❮](green)"

[git_branch]
symbol = "git "
format = "[$branch]($style)"
style = "bold purple"

[git_status]
format = "[[(*$conflicted$untracked$modified$staged$renamed$deleted)](218) ($ahead_behind$stashed)]($style)"
style = "bold purple"
conflicted = "​"
untracked = "​"
modified = "​"
staged = "​"
renamed = "​"
deleted = "​"
stashed = "≡"

[git_state]
format = '\([$state( $progress_current/$progress_total)]($style)\) '
style = "bright-black"

[cmd_duration]
format = "[$duration]($style) "
style = "yellow"

[username]
style_user = "bold green"
style_root = "bold red"
show_always = true
format = "[$user]($style)"

[hostname]
ssh_only = false
style = "bold yellow"
format = "[@](bold bright black)[$hostname]($style) "
disabled = false

[aws]
symbol = "aws "
format = "via [$symbol]($style)"

[azure]
symbol = "az "
format = "via [$symbol]($style)"

[bun]
symbol = "bun "
format = "via [$symbol]($style)"

[c]
symbol = "C "
format = "via [$symbol]($style)"

[cobol]
symbol = "cobol "
format = "via [$symbol]($style)"

[conda]
symbol = "conda "
format = "via [$symbol]($style)"

[crystal]
symbol = "cr "
format = "via [$symbol]($style)"

[cmake]
symbol = "cmake "
format = "via [$symbol]($style)"

[daml]
symbol = "daml "
format = "via [$symbol]($style)"

[dart]
symbol = "dart "
format = "via [$symbol]($style)"

[deno]
symbol = "deno "
format = "via [$symbol]($style)"

[dotnet]
symbol = ".NET "
format = "via [$symbol]($style)"

[docker_context]
symbol = "docker "

[elixir]
symbol = "exs "
format = "via [$symbol]($style)"

[elm]
symbol = "elm "
format = "via [$symbol]($style)"

[fennel]
symbol = "fnl "
format = "via [$symbol]($style)"

[fossil_branch]
symbol = "fossil "
format = "via [$symbol]($style)"

[gcloud]
symbol = "gcp "
format = "via [$symbol]($style)"

[gleam]
symbol = "gleam "
format = "via [$symbol]($style)"

[golang]
symbol = "go "
format = "via [$symbol]($style)"

[gradle]
symbol = "gradle "
format = "via [$symbol]($style)"

[guix_shell]
symbol = "guix "

[hg_branch]
symbol = "hg "

[java]
symbol = "java "
format = "via [$symbol]($style)"

[julia]
symbol = "jl "
format = "via [$symbol]($style)"

[kotlin]
symbol = "kt "
format = "via [$symbol]($style)"

[lua]
symbol = "lua "
format = "via [$symbol]($style)"

[nodejs]
symbol = "nodejs "
format = "via [$symbol]($style)"

[memory_usage]
symbol = "memory "

[meson]
symbol = "meson "

[nats]
symbol = "nats "

[nim]
symbol = "nim "

[nix_shell]
symbol = "nix "

[ocaml]
symbol = "ml "
format = "via [$symbol]($style)"

[opa]
symbol = "opa "

[os.symbols]
AIX = "aix "
Alpaquita = "alq "
AlmaLinux = "alma "
Alpine = "alp "
Amazon = "amz "
Android = "andr "
Arch = "rch "
Artix = "atx "
CentOS = "cent "
Debian = "deb "
DragonFly = "dfbsd "
Emscripten = "emsc "
EndeavourOS = "ndev "
Fedora = "fed "
FreeBSD = "fbsd "
Garuda = "garu "
Gentoo = "gent "
HardenedBSD = "hbsd "
Illumos = "lum "
Kali = "kali "
Linux = "lnx "
Mabox = "mbox "
Macos = "mac "
Manjaro = "mjo "
Mariner = "mrn "
MidnightBSD = "mid "
Mint = "mint "
NetBSD = "nbsd "
NixOS = "nix "
OpenBSD = "obsd "
OpenCloudOS = "ocos "
openEuler = "oeul "
openSUSE = "osuse "
OracleLinux = "orac "
Pop = "pop "
Raspbian = "rasp "
Redhat = "rhl "
RedHatEnterprise = "rhel "
RockyLinux = "rky "
Redox = "redox "
Solus = "sol "
SUSE = "suse "
Ubuntu = "ubnt "
Ultramarine = "ultm "
Unknown = "unk "
Void = "void "
Windows = "win "

[package]
symbol = "pkg "

[perl]
symbol = "pl "
format = "via [$symbol]($style)"

[php]
symbol = "php "
format = "via [$symbol]($style)"

[pijul_channel]
symbol = "pijul "

[pulumi]
symbol = "pulumi "

[purescript]
symbol = "purs "

[python]
symbol = "py "
format = "via [$symbol]($style)"

[quarto]
symbol = "quarto "

[raku]
symbol = "raku "

[ruby]
symbol = "rb "
format = "via [$symbol]($style)"

[rust]
symbol = "rs "
format = "via [$symbol]($style)"

[scala]
symbol = "scala "
format = "via [$symbol]($style)"

[spack]
symbol = "spack "

[solidity]
symbol = "solidity "

[status]
symbol = "[x](bold red) "

[sudo]
symbol = "sudo "

[swift]
symbol = "swift "
format = "via [$symbol]($style)"

[typst]
symbol = "typst "

[terraform]
symbol = "terraform "

[zig]
symbol = "zig "
format = "via [$symbol]($style)"
